### ISSUE TITLE
Web Application

### ISSUE THREAD

**Issue by mohamedsayed210** [bassemAgmi/EInvoicingSigner#10]
Hello Eng/Bassem
Now I have Web Applications Design by C# MVC and this web site is run live now and hosted on hostegator  domain host and database also on hostgetor mean all thing online 
Now i can send invoice to Tax authorities with version .09
now company bring Flash for Token and this usb flash connected to client pc 

can you you tell and help how i get signature from this usb to my website.
thanks...

**Comment by bassemAgmi** [comment]
You have to develop a desktop application on client machine to access the token. This application will integrate with your website using WEB API's.

**Comment by mohamedsayed210** [comment]
can i make windows applications to get token from usb flash at each time i send invoice and after this action save signature on remote database and get this key and add to document json ?

**Comment by bassemAgmi** [comment]
> can i make windows applications to get token from usb flash at each time i send invoice and after this action save signature on remote database and get this key and add to document json ?

yes, the windows application will retrieve the invoice json from the remote database, sign the invoice json using the token, abd send the invoice json with the signature to the remote database.

**Comment by mohamedsayed210** [comment]
Thank Eng /Bassem For Fast Reponse .
No i mean i create field in table invoice say Name Inv_Signuter And when user finsh and save this invoice and need to send to tax 
i call this windows application to get signature and update this filed on online database and start to send to tax via web Application.
or what's your recommendation

**Comment by bassemAgmi** [comment]
It is ok, please notice that you could not call windows application from web application. The windows application should be running on the client machine waiting for any new invoice added to the online database.
