### ISSUE TITLE
prompt for PIN every time

### ISSUE THREAD

**Issue by ramitofrederico** [bassemAgmi/EInvoicingSigner#2]
cms.ComputeSignature(signer) always prompt for PIN. how can it be silent? even when setting cms.ComputeSignature(signer, true) on Windows 10 it still prompt for the PIN

**Comment by bassemAgmi** [comment]
> cms.ComputeSignature(signer) always prompt for PIN. how can it be silent? even when setting cms.ComputeSignature(signer, true) on Windows 10 it still prompt for the PIN

could you share the code used to create the signer variable

**Comment by ramitofrederico** [comment]
It is the exact same code in this project on github. I just cloned it and ran it ... it always prompts for the PIN at this line:

SignedCms cms = new SignedCms(content);

I even tried to add the silent flag to true [  SignedCms cms = new SignedCms(content, true);  ] as the documentation says that it has effect on .net core projects and it does not prompt for the password. In reality it still prompts for the PIN. 

Any help? I am using the module "eps2003csp11.dll"

**Comment by ramitofrederico** [comment]
Hi Bassem .... Any news from your side?

**Comment by bassemAgmi** [comment]
1- please download the runtime version at https://drive.google.com/file/d/1jfkC_qfU56BSawRL4TcBrOssNudhcgTX/view?usp=sharing
2- extract the rar file to the folder D:\EInvoicing
3-update the file SubmitInvoices.bat by your token PIN. 
5-Run the file SubmitInvoices.bat as administrator.
check it will ask for the pin or not

**Comment by ramitofrederico** [comment]
Hi Bassem,

Thanks a lot for the file. I really appreciate your help. I tried it and it
works!! Great job!!

May you kindly share the source code (the one on github is probably old) as
I need to make some changes to how the signer works .. Specifically, I need
to pass the JSON document as argument and get the signed one in the stdout
not relying on the file system.

I am also curious to know which library you are using to access the
ePass2003 token .. I do not see the eps2003csp11.dll in the publish folder.

Thanks again for your help and sharing your knowledge with the developers
community.

Warm regards,
Ramy

**Comment by bassemAgmi** [comment]
The file code is the same code in github. The libray eps2003csp11.dll is located under system32 folder. if you try to invoke the code from a web application, check the web application execution user. The windows user used by your application server. if you are using asp, you need to impersonate your web site.
