### ISSUE TITLE
Signing documents with more than one token device on the same machine

### ISSUE THREAD

**Issue by ali7ussein** [bassemAgmi/EInvoicingSigner#38]
Hi Bassem,

First, I would like to thank you for the great e-invoice signing project really it is very helpful.

We have a machine with two signing token devices attached always sign function uses only one of the two devices while the login function is run on the other one so every time it tries to sign to the same token, Do you have a solution for this issue.

**Comment by mexx1988** [comment]
اعمل لوب من الأول على التوكنز لأنك أكيد بتتعامل على أول واحد يقابلك، لو تكتب كود هساعدك أكتر، وبص على الكود دة وحاول تفهمه.

```c#
Pkcs11InteropFactories factories = new Pkcs11InteropFactories();
using (IPkcs11Library pkcs11Library = factories.Pkcs11LibraryFactory.LoadPkcs11Library(factories, DllLibPath, AppType.MultiThreaded))
{
    var list = pkcs11Library.GetSlotList(SlotsType.WithTokenPresent).ToList();
    foreach (var slot in list)
    {
        ITokenInfo tokenInfo = slot.GetTokenInfo();

        if (tokenInfo.SerialNumber == "tokenSerialPerCompany") // or tokenInfo.Label & change token label in ePass
        {
            ISlotInfo slotInfo = slot.GetSlotInfo();
            //Do whatever you want
        }
    }
}
```

**Comment by ali7ussein** [comment]
Thanks @mexx1988 for your update, I was already opened the issue with OpenSC team https://github.com/OpenSC/OpenSC/issues/2890 and my main issue was that I am reading the tokens using the certificate issuer and all the tokens was from the same issuer once I started to ream them using the certificate Id the issue was resolved.
