### ISSUE TITLE
Support For G&D StarSign is needed

### ISSUE THREAD

**Issue by socertis** [bassemAgmi/EInvoicingSigner#8]
the e-invoice can be signed using one of both available, either by ePass2003 (which is supported now) or by G+D StarSign, which needs to be supported for the code to work with both token types.

**Comment by mrkindy** [comment]
Hello @socertis did you try using aetpkss1.dll instead of eps2003csp11.dll?

**Comment by socertis** [comment]
Yeah, and as i remember, it worked fine.
